apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-hostpath-pv  # Name of the PV
  namespace: default
spec:
  capacity:
    storage: 5Gi  # Define max storage size
  accessModes:
    - ReadWriteMany  # Allow multiple pods to write
  persistentVolumeReclaimPolicy: Retain  # Keep files even if pods delete
  storageClassName: manual  # Custom storage class
  hostPath:
    path: /home/ubuntu/spark-recordings  # Mount this host directory
